### ISSUE TITLE
Adding component view permissions to wiki pages?

### ISSUE THREAD

**Issue by platise** [trac-hacks/trac-componentpermissions#5]
There exist fine grained permissions which also offer a control over wiki pages. However the idea is, why not applying the same permissions to wiki pages, when a wiki page would be assigned some component? What do you think?

In my projects I write components in a form, to look at them as a place-holder for project export, holding tasks (tickets):
    component.subcomponent...subcomponent

separated with dots. So another improvement would be that whenever one types components separated with dots, component permission are only checked to that level, so:
 - Giving userA permission to see component, it inherits permissions from all subcomponents

**Comment by mitar** [comment]
I do not understand exactly what you mean by "wiki page assigned a component"? Components are part of a ticket system?

I use [this plugin](https://github.com/trac-hacks/trac-authzpolicy) for wiki access restrictions, which is then pretty easy to combine into groups with component-based permissions and then you have groups based on that?

**Comment by platise** [comment]
I couldn't found any doc related to this plugin. Can you provide an example how do you configure the access to wiki pages using this plugin?

**Comment by mitar** [comment]
If you would install it, you would see documentation in the Trac. But you can also see it here: https://github.com/trac-hacks/trac-authzpolicy/blob/master/authzpolicy/api.py#L34

**Comment by platise** [comment]
Thank you, let me try it.

**Comment by platise** [comment]
It indeed covers everything but in more complicated way.

Just to summarize the differences from AuthZ, the advantages I see:

 1. Using the TRAC ADMIN to assign permissions you already provided via COMPONENT_VIEW_....

 2. Components divide trac into a sub-projects, and wiki pages are used to describe this components, so we could have looked on wiki page as 'user manuals' for some components. So having an option to assign a wiki to some component from my eyes make sense? and then component_view permission would apply in addition to the defaultPermissions.

 3. Newly created wikis inherit permissions from where it is referenced from, this allows users to create wiki pages with component permission assigned.

**Comment by mitar** [comment]
This sounds an interesting idea, but a completely different plugin. You would first have to make a code for this "wiki belongs to a component" concept, and after that you could probably reuse some code from this and authz plugin.

**Comment by platise** [comment]
Ok, do you think we should promote this idea to trac-hacks, maybe somebody would get interested in to implement it?

**Comment by mitar** [comment]
I don't know but you can try.

**Comment by platise** [comment]
Will do, thanks for your support.

**Comment by rjollos** [comment]
I would highly recommend using `tracopt.perm.authz_policy` rather than trac-hacks/trac-authzpolicy. trac-hacks/trac-authzpolicy was branched from `tracopt.perm.authz_policy` at Trac 0.11 and there have been many improvements to `tracopt.perm.authz_policy` since Trac 0.11. If there are any signifiicant features in trac-authzpolicy that aren't found in `tracopt.perm.authz_policy`, it would be good to submit a patch to the Trac core (patch would ideally included tests). `tracopt.perm.authzpolicy` is documented on the [TracFineGrainedPermissions page](http://trac.edgewall.org/wiki/TracFineGrainedPermissions).

Regarding the feature of wiki page belongs to a component, you may want to look at [Trac#1233](http://trac.edgewall.org/ticket/1233). That is forthcoming in Trac 1.2 (~July 2015). With Components becoming first-class objects in the ticket system, similar to milestones, perhaps you won't need a wiki page for each Component?

I haven't looked closely at this plugin, but if you wish to apply a `COMPONENT` permission to wiki pages, that could also be done with a permissions policy plugin. I suggest asking on the [MailingList](http://trac.edgewall.org/wiki/MailingList) if you are interested in that approach.

**Comment by platise** [comment]
Thanks for tips, and the permissions policy plugin. I will have a look.

Regarding the #1233 above concept could also fit, as for each ticket which is assigned to some component, wiki pages could be extracted, as they would be assigned to some components unless dangling as now. So the tip for each component could be given, and of course starting with the most root wiki pages, which can be found from the references. Not all components need wiki's but it is good that each component is described somewhere.

Here a method of component classes could help. At the moment component infrastructure is flat. So I am writing them as component.subcomponent.subcomponent.... with dots. This component view permission plugin correctly handles dots and replaces them with _. In this way I organize task containers, a structure which is ready to be exported to TaskJuggler for planning and tracking. So that means that a permission for component could imply permissions for sub-components, as well as in a search for a wiki pages.
